// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

// TICKET
export const GET_TICKET = 'GET_TICKET';
export const GET_TICKETS = 'GET_TICKETS';
export const SAVE_TICKET = 'ADD_NEW_TICKET';
export const EDIT_TICKET = 'EDIT_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const GET_TICKET_COMMENTS = 'GET_TICKET_COMMENTS';
export const REPLACE_IMAGE_URL = 'REPLACE_IMAGE_URL';

// COMMENT
export const SAVE_COMMENT = 'SAVE_COMMENT';

// FIRST IT NEEDS CREATE API
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

